fix: Change wrong log level in cluster.go openAPISchema, gvkParser
argoproj/gitops-engine pull request #430
Opened 2022-07-13 13:28 UTC by dllegru

Fixes argoproj/gitops-engine#423

Change wrong log level from `Error` to `Warning`.

2022-07-25 14:47 UTC, leoluz commented
@dllegru The reason why I added the log as `Error` is because the log interface doesn't have the `Warning` method. This is why your PR is failing with error:

```
pkg/cache/cluster.go:733: c.log.Warning undefined (type logr.Logger has no field or method Warning)
```

2022-07-29 11:52 UTC, dllegru commented
> @dllegru The reason why I added the log as `Error` is because the log interface doesn't have the `Warning` method. This is why your PR is failing with error:
> 
> ```
> pkg/cache/cluster.go:733: c.log.Warning undefined (type logr.Logger has no field or method Warning)
> ```
> 
> We need to define and implement this method. Would you be willing to go ahead and update your PR with this implementation?

I'm sorry @leoluz but my current experience with Golang at the moment is close to 0, so can't help much at this stage.

2022-07-29 15:51 UTC, leoluz commented
@dllegru No problem.. I dug a bit and realized that the problem is actually caused by the library we use that [doesn't provide a log.Warning](https://github.com/go-logr/logr/blob/b359493a99cc734afcafd0dec505149d07f78ae1/README.md#why-not-named-levels-like-infowarningerror) method.
If you can just change the log to `Info` in your PR it will work and it should be fine to merge. Also, if you are updating your  PR pls don't forget to signoff your commits (git commit -sm 'commit message') or the DCO check will fail.
Thank you.

2022-08-02 14:33 UTC, dllegru commented
Hi @leoluz, thanks for digging into it and sharing the documentation, it's very insightftul.
I've changed to `c.log.Info` as suggested although the tests now fail with:
```
Error: pkg/cache/cluster.go:669:18: cannot use e (type *kube.CreateGVKParserError) as type string in argument to c.log.Info
Error: pkg/cache/cluster.go:733:13: cannot use e (type *kube.CreateGVKParserError) as type string in argument to c.log.Info
```
It seems the problem is in using string format var `e`  cannot be used with `c.log.Info`. I'm sorry can't provide much more help at this moment due my lack of knowledge with Go.

2022-08-02 15:30 UTC, leoluz requested changes
Please take a look at the change suggestions to fix the build.

2022-08-02 15:30 UTC, leoluz commented on pkg/cache/cluster.go
> +							c.log.Info(e, "warning loading openapi schema")
Please replace this line with:
`c.log.Info("warning loading openapi schema: %s", e)`

2022-08-02 15:30 UTC, leoluz commented on pkg/cache/cluster.go
> +		c.log.Info(e, "warning loading openapi schema")
Please replace this line with:
`c.log.Info("warning loading openapi schema: %s", e)`

2022-08-02 15:53 UTC, leoluz commented
CI/Test job is now passing. Thank you.
You still need to signoff your commits for me the approve/merge. You can do so by running the following commands in your terminal:

```
git rebase HEAD~3 --signoff
git push --force-with-lease origin 425_error_creating_gvk_parser
```

2022-08-02 16:24 UTC, dllegru commented
> CI/Test job is now passing. Thank you. @dllegru You still need to signoff your commits for me to approve/merge. You can do so by running the following commands in your terminal:
> 
> ```
> git rebase HEAD~3 --signoff
> git push --force-with-lease origin 425_error_creating_gvk_parser
> ```

Many thanks to you @leoluz! 
I've rebased all the commits, as you pointed I had a missing sign-off message (thanks for the command) in a previous commit and also the email address was wrongly set-up.

I think finally all looks good now! 🥳

2022-08-02 17:10 UTC, leoluz approved these changes
LGTM

2022-08-02 17:10 UTC, merged