Fixed server side flag to false when rerunning in dry run in client mode
argoproj/gitops-engine pull request #563
Opened 2024-01-14 15:59 UTC by anandf

2024-01-14 16:27 UTC, anandf commented
#### Steps to reproduce the error
- Create the kind cluster
```
# kind create cluster --name argocd
```
- Install the 2.10.0-rc1 version of argocd in `argocd` namespace
```
# kubectl create ns argocd && kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0-rc1/manifests/install.yaml -n argocd
```
- Update the image containing the fix
```
# argocd app create guestbook --core --repo https://github.com/anandf/argocd-example-apps.git \
--path kustomize-guestbook \
--dest-namespace guestbook \
--dest-server https://kubernetes.default.svc \
--sync-policy automated \
--self-heal \
--sync-option CreateNamespace=true \
--sync-option ServerSideApply=true
# argocd app list --core
```
The argocd application `guestbook` will fail to sync and will have the sync failed status with message`namespace \'guestbook\' not found`

2024-01-14 16:27 UTC, anandf commented
#### Steps to build the fix
- Clone the `argo-cd` repo for branch `release-2.10`
```
# git clone -b release-2.10 git@github.com/argoproj/argo-cd
```
- Update the go.mod file to pick the gitops-engine library containing the fix
````
# go mod edit -replace github.com/argoproj/gitops-engine=github.com/anandf/gitops-engine b39d57e63236b3f430a8b229514f76a5a53f5d46
# go mod tidy
````
- Build the argocd image and push it to quay or docker>
````
# export QUAY_USER=<quay_userid>
# IMAGE_PREFIX=quay.io/$QUAY_USER/ make image && docker push quay.io/$QUAY_USER/argocd:latest
````

#### Steps to apply the fix and validate
- Delete and recreate the kind cluster
```
# kind delete cluster --name argocd
# kind create cluster --name argocd
```
- Install the 2.10.0-rc1 version of argocd in `argocd` namespace
```
# kubectl create ns argocd && kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0-rc1/manifests/install.yaml -n argocd
```
- Update the image containing the fix
```
# kubectl set image -n argocd statefulset argocd-application-controller *=quay.io/$QUAY_USER/argocd:latest
```
- Wait for the rollout to complete and create the application
```
kubectl rollout status statefulset/argocd-application-controller -n argocd
```
- Creat the application with `syncOptions` `CreateNamespace=true` and `ServerSideApply=true` as below
```
# argocd app create guestbook --core --repo https://github.com/anandf/argocd-example-apps.git \
--path kustomize-guestbook \
--dest-namespace guestbook \
--dest-server https://kubernetes.default.svc \
--sync-policy automated \
--self-heal \
--sync-option CreateNamespace=true \
--sync-option ServerSideApply=true
# argocd app list --core
```
The application should get synced and reach an healthy state with the fix

2024-01-16 12:20 UTC, pasha-codefresh commented
@anandf thank you for your PR. Last time when i have fixed this issue https://github.com/argoproj/argo-cd/issues/16177
in these PRs
https://github.com/argoproj/gitops-engine/pull/548
https://github.com/argoproj/gitops-engine/pull/546

In high level
Argocd always used client side dry run for both, client and server apply. I have noticed only issue with hooks that i described originally and for compatibility we decided not to change how it worked before if error occur. 
Before my fix it always took server side apply with client side dry run. 

Could you please confirm that before my changes you were not able reproduce this issue? Because with your change you also going to change how you applying resources and customer even will not know that they doing it with client side apply.

Thanks!

2024-01-16 16:35 UTC, leoluz commented
> Could you please confirm that before my changes you were not able reproduce this issue? Because with your change you also going to change how you applying resources and customer even will not know that they doing it with client side apply.

@pasha-codefresh This change will only affect the sync during dryrun with strategy `DryRunServer`. It doesn't seem to change how Argo CD actually applies the resource in the cluster. Can you please take another look in his changes and confirm?

2024-01-16 22:32 UTC, pasha-codefresh commented
> > Could you please confirm that before my changes you were not able reproduce this issue? Because with your change you also going to change how you applying resources and customer even will not know that they doing it with client side apply.
> 
> 
> 
> @pasha-codefresh This change will only affect the sync during dryrun with strategy `DryRunServer`. It doesn't seem to change how Argo CD actually applies the resource in the cluster. Can you please take another look in his changes and confirm?

Yes, you are right , lgtm

2024-01-17 04:07 UTC, anandf commented on pkg/sync/sync_context.go
> +	applyFn := func(dryRunOption cmdutil.DryRunStrategy, serverSideApplyFlag bool) (string, error) {
I have reverted it back to `dryRunStrategy`. I was under the impression that the func arg was shadowing the outer scope variable `dryRunStrategy` and decided to have a different name for the function arg. But my impression was not true and the linter did not complain about the variable shadowing.

2024-01-17 04:08 UTC, anandf commented on pkg/sync/sync_context.go
> +		sc.log.Info(fmt.Sprintf("calling applyFn using dry run strategy: %v and server side apply %v", dryRunOption, serverSideApplyFlag))
Thanks for pointing this out. I have changed the log level now.

2024-01-17 16:54 UTC, leoluz requested changes
A did more investigation and I don't think that we should be going in this direction.
[Explanation here](https://github.com/argoproj/argo-cd/issues/13874#issuecomment-1896203996)

2024-01-22 11:28 UTC, anandf commented
Taking a different approach and created a new PR https://github.com/argoproj/gitops-engine/pull/564

2024-01-23 20:39 UTC, leoluz commented
Closing in favour of https://github.com/argoproj/gitops-engine/pull/564

2024-01-23 20:39 UTC, closed without merging